/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: '#FBFBF9',
        surface: '#FBFBF9',
        ink: '#1A1A18',
        muted: '#55534D',
        subtle: '#807D75',
        rule: '#DAD8D1',
        'soft-rule': '#E9E7E0',
        accent: '#6B2B2B',
        'accent-hover': '#4F1F1F',
        secondary: '#5C5A53',
        success: '#3A5A40',
        'code-bg': '#F3F2EC',
      },
      borderRadius: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '9999px',
      },
      fontFamily: {
        serif: [
          'Source Serif 4',
          'Source Serif Pro',
          'Charter',
          'Georgia',
          'Cambria',
          'serif',
        ],
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'IBM Plex Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'monospace',
        ],
      },
      fontSize: {
        xs: ['12px', '1.5'],
        sm: ['14px', '1.6'],
        base: ['16px', '1.75'],
        lg: ['18px', '1.75'],
        xl: ['20px', '1.6'],
        '2xl': ['24px', '1.4'],
        '3xl': ['30px', '1.3'],
        '4xl': ['36px', '1.2'],
        '5xl': ['48px', '1.1'],
        '6xl': ['60px', '1.05'],
        '7xl': ['72px', '1.02'],
      },
      lineHeight: {
        relaxed: '1.75',
        loose: '1.875',
      },
      letterSpacing: {
        tighter: '-0.025em',
        tight: '-0.015em',
        normal: '0',
        wide: '0.025em',
        wider: '0.08em',
        widest: '0.18em',
      },
      maxWidth: {
        prose: '68ch',
        narrow: '55ch',
        wide: '76ch',
      },
      fontVariantNumeric: {
        'tabular-nums': 'tabular-nums',
      },
    },
  },
  plugins: [],
};
